version: "3.9"

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: adml
    ports:
      - "80:80"
    environment:
      DATABASE_URL: "mysql+pymysql://huerji%40adproject-database:HuErJi123@adproject-database.mysql.database.azure.com:3306/adproject?ssl=true"
    volumes:
      - .:/app   # 挂载当前目录，支持代码热更新
    command: uvicorn app.main:app --host 0.0.0.0 --port 80 --reload
