version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:80"
    environment:
      - MYSQL_HOST=adproject-database.mysql.database.azure.com
      - MYSQL_USER=huerji@adproject-database
      - MYSQL_PASSWORD=HuErJi123
      - MYSQL_DB=adproject
