name: Build and deploy Python app to Azure Web App - ADProjectML

on:
  push:
    branches:
      - master
  workflow_dispatch:

concurrency:
  group: azure-deploy
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      # 1. 拉取代码
      - uses: actions/checkout@v4

      # 2. 设置 Python 版本
      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # 3. 创建虚拟环境并安装生产依赖
      - name: Create and install dependencies
        run: |
          python -m venv antenv
          source antenv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      # 4. 安装测试依赖并运行测试
      - name: Install test dependencies
        run: |
          pip install -r requirements-test.txt
          pytest

      # 5. 上传完整项目（包含已装好的虚拟环境）
      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            .
            !**/__pycache__/

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # 6. 下载构建好的项目
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      # 7. 部署到 Azure（带已装好的虚拟环境）
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'ADProjectML'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_AB5317419523461E9B0268C946BB7FC1 }}
